// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHXXb-uJZgIbe2mDrw2GB9e41046ZOiI',
    appId: '1:214288023465:web:a611042de8c3061d0fceb8',
    messagingSenderId: '214288023465',
    projectId: 'flutter-74058',
    authDomain: 'flutter-74058.firebaseapp.com',
    databaseURL: 'https://flutter-74058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-74058.appspot.com',
    measurementId: 'G-QS7LCMHWYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFYGbwK-JRNm7NdWFXUXQNa0Wucf5lpU',
    appId: '1:214288023465:android:f485f8c6a227dac70fceb8',
    messagingSenderId: '214288023465',
    projectId: 'flutter-74058',
    databaseURL: 'https://flutter-74058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-74058.appspot.com',
  );
}
